# Generated by Django 3.1.5 on 2021-01-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
